### ISSUE TITLE
[BUG] - When clicking on Activate button in development mode

### ISSUE THREAD

**Issue by vnetonline** [oqtane/Oqtane.LicensedModule#1] opened 2024-06-04 20:58 UTC
Oqtane Info

Version - 5.1.1
Render Mode - Static
Interactivity - Server
Database - SQL Server

Describe the bug

I have released a commercial module called Amazing Subscriber
While testing the module in the local development environment using the licensing=testmode parameter
There is no option to enter the license manual
Expected Behavior

There should be an ability to manually enter a license key and click Validate as the documentation says.
Steps To Reproduce

Include the licensing module in your project and try it
Anything else?

I have setup the product to test in the Sandbox

**Comment by sbwalker** [comment] 2024-06-04 21:01
Please provide the exact Url you are using in your environment

**Comment by vnetonline** [comment] 2024-06-04 21:09
It is in development environment https://localhost:44357/?licensing=testmode

The licensed module Amazing.Module.Subscriber is on homepage

**Comment by sbwalker** [comment] 2024-06-04 21:11
and when you look in the /bin folder you are sure that a license has not already been generated for the module (ie. no Amazing.Module.Subscriber.lic file exists)?

**Comment by sbwalker** [comment] 2024-06-04 21:18
actually it appears there is an issue which was caused when adding support for static rendering which affects the testmode parameter

**Comment by vnetonline** [comment] 2024-06-05 01:51
@sbwalker are you planning to fix this ?

need to use the module on my production sites so need to activate keys manually

**Comment by vnetonline** [comment] 2024-06-05 09:21
@sbwalker no rush ... I have generated the keys manually and created the lic files and uploaded them to my production sites bin folder and they are now working

**Comment by sbwalker** [comment] 2024-06-05 11:51
@vnetonline the problem you reported should only exist in your development site (ie. localhost). In a production site, the ability to enter a license key should work fine. Please let me know if this is not the case.

**Comment by vnetonline** [comment] 2024-06-05 13:02
@sbwalker this is not the case in my production environment when I click Activate nothing happens the Purchase button works and it directs me to the order page.

**Comment by sbwalker** [comment] 2024-06-05 13:54
Ok, I will explore further

**Comment by sbwalker** [comment] 2024-06-05 14:31
@vnetonline I am unable to reproduce the problem you are describing. I am assuming you are using the latest version of the Oqtane.Licensing component - version 5.1.0 (https://www.nuget.org/packages/Oqtane.Licensing/5.1.0)?

If the integration with your module is specifying the PackageName parameter correctly, and you are running in a local environment, and you have specified the "licensing=testmode" querystring parameter, then the licensing component should display a message which says "Amazing Subscriber Is Not Licensed" and below it, an Activate and Purchase button should be visible. Are you able to to post a screen shot of this UI from your local installation?

When you click the Activate button, the UI should change and display a form with a Fetch button, a license key text box, and a Validate button. The text box is where a license key can be manually entered and clicking Validate will validate the license key. Can you also post a screen shot of this UI containing the license key textbox (without the actual license key value) from your local installation?

These screen shots will help me diagnose the issue you are experiencing.

**Comment by vnetonline** [comment] 2024-06-06 06:41
@sbwalker I updated the Oqtane.Licensing  to 5.1.0 from 5.0.1 and everything works as expected, 

The documentation was not correct it mentions to use 5.0.1, so I have submitted a pull request with images as to what developers should expect when they pass in the `?licenising=testmode` parameter on the page on which the module in their local environment to test the license flow.

**Comment by sbwalker** [comment] 2024-06-06 15:16
closing as this is not an issue

**Closed as completed by sbwalker** 2024-06-06 15:16 UTC
